version: '3'

services:
  fastapi:
    container_name: fast-api
    restart: always
    build:
      context: ./api
    
    env_file:
      - ./api/.env
    ports:
      - "8001:8001"
      
    volumes:
      - ./api:/usr/src/app
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/init-scripts:/docker-entrypoint-initdb.d
  django:
    container_name: django-app
    restart: always
    build:
      context: ./hr_app
 
    env_file:
      - ./hr_app/.env
    ports:
      - "8000:8000"
      
    depends_on:
      - fastapi
    volumes:
      - ./hr_app:/app


      
