version: '3'

services:
  fastapi:
    container_name: fast-api
    restart: always
    build:
      context: ./api
    environment:
      - API_KEY_NAME=X-API-Key
      - API_KEY=1234
      - MAX_CALLS=10
      - TIME_FRAME=60
      - DB_USER=postgres
      - DB_PASSWORD=1234
      - DB_HOST=postgres
    # env_file:
    #   - ./api/.env
    ports:
      - "8001:8001"
      
    volumes:
      - ./api:/usr/src/app
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/init-scripts:/docker-entrypoint-initdb.d
  
  django:
    container_name: django-app
    restart: always
    build:
      context: ./hr_app
    environment:
      - API_KEY=1234
      - API_KEY_NAME=X-API-Key
      - API_URL_FE=http://localhost:8001/v1/
      - API_URL=http://fastapi:8001/v1/
    # env_file:
    #   - ./hr_app/.env
    ports:
      - "8000:8000"
      
    depends_on:
      - fastapi
    volumes:
      - ./hr_app:/app


      
